insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (1, 'Mechanical Systems Engineer', 'Encounter for screening for other diseases and disorders');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (2, 'Tax Accountant', 'Burn of first degree of back of right hand');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (3, 'General Manager', 'Unsp fracture of right femur, init for clos fx');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (4, 'Automation Specialist II', 'Major laceration of left vertebral artery, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (5, 'Editor', 'Nondisp fx of ant pro of r calcaneus, 7thD');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (6, 'Staff Accountant I', 'Contact w unsp sharp object, undetermined intent, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (7, 'Data Coordiator', 'Displ apophyseal fx unsp femur, subs for clos fx w malunion');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (8, 'Environmental Tech', 'Nondisp transverse fx shaft of l fibula, 7thK');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (9, 'Automation Specialist III', 'Disp fx of pisiform, left wrist, subs for fx w routn heal');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (10, 'Clinical Specialist', 'Toxic effect of phosphorus and its compnd, self-harm, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (11, 'Director of Sales', 'Retained foreign body in right lower eyelid');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (12, 'Assistant Manager', 'Diphtheritic conjunctivitis');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (13, 'Junior Executive', 'Pathological fracture in oth disease, right tibia, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (14, 'Software Engineer II', 'Disp fx of med condyle of unsp tibia, 7thK');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (15, 'Financial Analyst', 'Poisoning by antiviral drugs, undetermined, init encntr');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (16, 'Computer Systems Analyst II', 'Malignant neoplasm of vagina');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (17, 'VP Sales', 'Maternal care for anti-D antibodies, unspecified trimester');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (18, 'Media Manager IV', 'Adverse effect of other hormone antagonists');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (19, 'Developer III', 'Intentional self-harm by blunt object, initial encounter');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (20, 'Web Developer II', 'Poisoning by coronary vasodilators, self-harm, subs');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (21, 'Data Coordiator', 'Open bite of unsp bk wl of thorax w penet thor cavity, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (22, 'VP Marketing', 'Contusion of nose, initial encounter');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (23, 'Clinical Specialist', 'War operations involving oth explosions and fragments, milt');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (24, 'Media Manager III', 'Cereb infrc due to embolism of left middle cerebral artery');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (25, 'Senior Financial Analyst', 'Sltr-haris Type II physl fx low end r fibula, 7thG');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (26, 'Mechanical Systems Engineer', 'Disp fx of unsp radial styloid pro, 7thD');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (27, 'Account Coordinator', 'Insect bite of unsp external genital organs, female');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (28, 'Administrative Officer', 'Dislocation of MCP joint of left index finger, subs');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (29, 'Graphic Designer', 'Pre-exist hyp chronic kidney disease comp preg, third tri');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (30, 'Chief Design Engineer', 'Inj deep peroneal nrv at ank/ft level, unsp leg, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (31, 'Teacher', 'Nondisp fx of medial phalanx of left index finger, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (32, 'Nurse', 'Contusion of fallopian tube, unilateral');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (33, 'Speech Pathologist', 'Puncture wound w/o foreign body of left hand, subs encntr');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (34, 'Biostatistician II', 'Osteonecrosis due to previous trauma');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (35, 'Help Desk Operator', 'Pathological fracture, right tibia, subs for fx w malunion');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (36, 'VP Accounting', 'Driver of dune buggy injured in nontraffic accident, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (37, 'Pharmacist', 'Nondisp bimalleol fx unsp low leg, init for opn fx type I/2');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (38, 'Research Assistant II', 'Lead-induced chronic gout, unspecified shoulder');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (39, 'Software Test Engineer III', 'Burns of 20-29% of body surfc w 0% to 9% third degree burns');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (40, 'Staff Accountant IV', 'Implantation cysts of iris, ciliary body or anterior chamber');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (41, 'Marketing Manager', 'Poisoning by unsp narcotics, undetermined, subs encntr');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (42, 'Help Desk Technician', 'Traumatic amputation of ear');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (43, 'Social Worker', 'Unspecified injury of plantar artery of unspecified foot');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (44, 'VP Product Management', 'Injury of digital nerve of right thumb, initial encounter');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (45, 'Chemical Engineer', 'Unspecified injury of muscle, fascia and tendon of abdomen');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (46, 'Actuary', 'Bladder disorders in diseases classified elsewhere');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (47, 'VP Product Management', 'Stress fx, unsp ulna and radius, subs for fx w nonunion');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (48, 'Nuclear Power Engineer', 'Other open wound of other specified part of neck');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (49, 'Statistician IV', 'Contus/lac/hem crblm w LOC of 6 hours to 24 hours, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (50, 'Programmer Analyst IV', 'Nondisp fx of lunate, unsp wrist, subs for fx w delay heal');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (51, 'Paralegal', 'Person outside 3-whl mv inj in clsn w ped/anml nontraf, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (52, 'Data Coordiator', 'Nondisp transverse fx shaft of unsp femr, 7thG');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (53, 'Accountant IV', 'Traumatic rupture of oth ligament of right wrist, subs');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (54, 'Assistant Media Planner', 'Adverse effect of other parasympathomimetics, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (55, 'Food Chemist', 'Unsp fx low end l ulna, 7thE');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (56, 'Chief Design Engineer', 'Injury of digital nerve of unspecified finger, subs encntr');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (57, 'Design Engineer', 'Strain of intrinsic musc/fasc/tend finger at wrs/hnd lv');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (58, 'VP Accounting', 'Other marginal perforations of tympanic membrane, left ear');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (59, 'Food Chemist', 'Anterior cord syndrome at C6, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (60, 'Account Coordinator', 'Personality disorder, unspecified');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (61, 'VP Accounting', 'Nondisp apophyseal fx unsp femr, 7thF');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (62, 'VP Marketing', 'Contusion of sigmoid colon, initial encounter');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (63, 'Quality Control Specialist', 'Oth injury of right quadriceps muscle, fascia and tendon');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (64, 'Pharmacist', 'Dislocation of unsp interphalangeal joint of r mid finger');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (65, 'VP Accounting', 'Chronic embolism and thrombosis of deep vn unsp up extrem');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (66, 'Programmer II', 'Prsn brd/alit a car injured in collision w ped/anml, subs');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (67, 'Software Engineer III', 'Pnctr w/o fb of unsp external genital organs, female');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (68, 'Office Assistant III', 'Zoster encephalitis');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (69, 'Dental Hygienist', 'Foreign body granuloma of soft tissue, NEC, left ank/ft');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (70, 'Help Desk Technician', 'Hemiplegic migraine, not intractable, w/o status migrainosus');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (71, 'VP Product Management', 'Rheumatoid heart disease w rheumatoid arthritis of left hand');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (72, 'Dental Hygienist', 'Minor laceration of unsp innominate or subclav art, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (73, 'Account Executive', 'Unspecified sprain of left lesser toe(s)');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (74, 'Technical Writer', 'Nondisp fx of prox 3rd of navic bone of r wrs, 7thB');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (75, 'Geologist II', 'Subluxation and disloc of proximal interphaln joint of thumb');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (76, 'Physical Therapy Assistant', 'Discitis, unspecified, thoracolumbar region');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (77, 'Web Developer I', 'Accidental handgun discharge, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (78, 'Sales Representative', 'Unspecified injury of splenic vein, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (79, 'Compensation Analyst', 'Unsp inj extn/abdr musc/fasc/tend of r thm at forarm lv');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (80, 'Research Associate', 'Nondisplaced apophyseal fracture of unspecified femur');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (81, 'Internal Auditor', 'Burn of internal genitourinary organs');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (82, 'Actuary', 'Other serum reaction due to other serum, initial encounter');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (83, 'Accounting Assistant III', 'Contus/lac cereb, w/o loss of consciousness, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (84, 'Internal Auditor', 'Terrorism involving chemical weapons');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (85, 'Recruiting Manager', 'Oth disp fx of upr end unsp humer, subs for fx w delay heal');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (86, 'Media Manager I', 'Dislocation of other parts of unsp shoulder girdle, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (87, 'Director of Sales', 'Open wound of ankle, foot and toes');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (88, 'Design Engineer', 'Nondisp Rolando''s fracture, r hand, subs for fx w delay heal');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (89, 'General Manager', 'Open bite, left foot, initial encounter');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (90, 'Professor', 'Atyp squam cell of undet signfc cyto smr crvx (ASC-US)');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (91, 'Pharmacist', 'Complex tear of lat mensc, current injury, left knee, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (92, 'Marketing Manager', 'Unspecified open wound, unspecified lower leg, init encntr');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (93, 'Operator', 'Unsp fx navicular bone of left wrist, subs for fx w malunion');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (94, 'Project Manager', 'Nondisp fx of med condyle of l tibia, 7thR');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (95, 'Geologist III', 'Laryngocele');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (96, 'Product Engineer', 'Food in bronchus causing asphyxiation, initial encounter');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (97, 'Software Engineer II', 'Carcinoma in situ of other and unspecified genital organs');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (98, 'Director of Sales', 'Sltr-haris Type III physeal fx lower end radius, right arm');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (99, 'Systems Administrator I', 'Open bite of left ring finger w/o damage to nail, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (100, 'Compensation Analyst', 'Toxic effect of unsp gases, fumes and vapors, undet, subs');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (101, 'Tax Accountant', 'Other obstetric embolism');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (102, 'Editor', 'Menstrual migraine, intractable');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (103, 'Financial Advisor', 'Persistent cloaca');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (104, 'Occupational Therapist', 'Fracture of subcondylar process of right mandible');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (105, 'Web Developer III', 'Abrasion, unspecified hip');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (106, 'Database Administrator I', 'Laceration w/o fb of right cheek and TMJ area, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (107, 'VP Product Management', 'Juvenile arthritis, unspecified, unspecified elbow');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (108, 'Information Systems Manager', 'Sltr-haris Type II physl fx low end rad, l arm, 7thG');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (109, 'Senior Sales Associate', 'Pasngr in hv veh inj in clsn w statnry object in traf, subs');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (110, 'Associate Professor', 'Crushing injury of unspecified hip, initial encounter');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (111, 'Recruiting Manager', 'Abscess of tendon sheath, upper arm');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (112, 'General Manager', 'Intraop and postprocedural complications of the spleen');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (113, 'Database Administrator IV', 'Malar fracture, right side, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (114, 'Computer Systems Analyst III', 'Contact with nonvenomous snakes');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (115, 'Accounting Assistant II', 'Displ seg fx shaft of l femr, 7thR');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (116, 'Programmer Analyst IV', 'Nondisp pilon fx r tibia, 7thH');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (117, 'General Manager', 'Sprain of metacarpophalangeal joint of unsp finger, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (118, 'Executive Secretary', 'Periumbilical pain');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (119, 'Nurse', 'Oth Rh incompat reaction due to transfusion of bld/bld prod');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (120, 'Desktop Support Technician', 'Poisoning by unspecified psychodysleptics, assault');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (121, 'Editor', 'Oth fx upper end of unsp ulna, init for opn fx type 3A/B/C');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (122, 'Social Worker', 'Hereditary nephropathy, not elsewhere classified');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (123, 'Analyst Programmer', 'Disease of pancreas, unspecified');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (124, 'VP Sales', 'Laceration w/o fb of right thumb w/o damage to nail, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (125, 'Nurse', 'Burn of 2nd deg mul sites of left wrist and hand, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (126, 'Office Assistant IV', 'Superficial frostbite of right foot');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (127, 'Assistant Professor', 'Acquired clawhand, left hand');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (128, 'Accountant II', 'Rheumatoid myopathy with rheumatoid arthritis of right knee');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (129, 'Software Test Engineer I', 'Carrier of bacterial disease due to staphylococci');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (130, 'Research Nurse', 'Displ spiral fx shaft of rad, unsp arm, 7thE');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (131, 'Community Outreach Specialist', 'Hemarthrosis, unspecified wrist');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (132, 'Budget/Accounting Analyst II', 'Major laceration of right internal jugular vein');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (133, 'Registered Nurse', 'Pathological fracture, right finger(s), init for fx');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (134, 'Compensation Analyst', 'Posterior dislocation of lens, unspecified eye');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (135, 'Junior Executive', 'Asymptomatic neurosyphilis');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (136, 'GIS Technical Architect', 'Unspecified fracture of the lower end of radius');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (137, 'Marketing Assistant', 'Anterior subluxation and dislocation of sternoclav jt');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (138, 'Structural Engineer', 'Polyphagia');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (139, 'GIS Technical Architect', 'Nondisp bimalleol fx unsp low leg, 7thF');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (140, 'Director of Sales', 'Path fracture, left finger(s), subs for fx w nonunion');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (141, 'Statistician II', 'Other synovitis and tenosynovitis, right hand');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (142, 'Operator', 'Inj great saphenous at lower leg level, left leg, subs');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (143, 'Quality Control Specialist', 'Age-related cataract, morgagnian type, left eye');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (144, 'Environmental Specialist', 'Inj musc/tend peroneal grp at low leg level, unsp leg, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (145, 'Business Systems Development Analyst', 'Oth ultralt/microlt/pwr-glider acc injuring occupant, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (146, 'Administrative Officer', 'Nondisp fx of greater trochanter of right femur, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (147, 'Systems Administrator IV', 'Other superficial bite of left forearm, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (148, 'Structural Analysis Engineer', 'Sltr-haris Type II physeal fx lower end of unsp tibia, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (149, 'Biostatistician IV', 'Contact with other hot fluids, subsequent encounter');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (150, 'Desktop Support Technician', 'Osteonecrosis in diseases classified elsewhere, right thigh');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (151, 'Teacher', 'Other specified disorders of choroid');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (152, 'Actuary', 'Traction detachment of retina');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (153, 'Clinical Specialist', 'Nondisp fx of distal pole of navic bone of unsp wrist, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (154, 'Assistant Media Planner', 'Nondisp unsp fx unsp lesser toe(s), subs for fx w routn heal');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (155, 'Geologist I', 'Poisn by local antifung/infect/inflamm drugs, slf-hrm, sqla');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (156, 'Editor', 'Cephalhematoma due to birth injury');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (157, 'Clinical Specialist', 'Transverse fracture of acetabulum');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (158, 'Automation Specialist I', 'Mtrcy pasngr inj in clsn w statnry object nontraf, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (159, 'Product Engineer', 'Superficial frostbite of unspecified wrist');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (160, 'Geologist III', 'Oth injury of popliteal vein, unspecified leg, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (161, 'Environmental Tech', 'Pyothorax with fistula');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (162, 'Programmer Analyst I', 'Rh incompat reaction due to transfuse of bld/bld prod, unsp');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (163, 'Software Engineer IV', 'Fourth degree hemorrhoids');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (164, 'Food Chemist', 'Disp fx of shaft of second metacarpal bone, right hand');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (165, 'Research Assistant I', 'Inj extn musc/fasc/tend at forearm level, left arm, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (166, 'Dental Hygienist', 'Maternal care for oth isoimmunization, first trimester, unsp');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (167, 'Senior Developer', 'Sltr-haris Type III physl fx low end ulna, l arm, 7thD');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (168, 'Actuary', 'Olecranon bursitis, unspecified elbow');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (169, 'Financial Advisor', 'Disp fx of nk of unsp rad, 7thJ');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (170, 'GIS Technical Architect', 'Other specified injuries of right foot, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (171, 'Executive Secretary', 'Primary lacrimal gland atrophy, left lacrimal gland');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (172, 'Assistant Manager', 'Postproc seroma of a nervous sys org fol a nervous sys proc');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (173, 'Web Developer IV', 'Sec and unsp malig neoplasm of nodes of multiple regions');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (174, 'Senior Financial Analyst', 'Nondisp fx of lateral condyle of r femr, 7thB');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (175, 'Marketing Assistant', 'Displacement of artificial skin grft /decellular alloderm');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (176, 'Human Resources Assistant III', 'Fracture of unsp phalanx of r idx fngr, init for opn fx');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (177, 'Nuclear Power Engineer', 'Immersion foot, left foot');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (178, 'Assistant Media Planner', 'Subluxation of L2/L3 lumbar vertebra, initial encounter');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (179, 'Assistant Professor', 'Traum hemor r cereb w LOC >24 hr w/o ret consc w surv, subs');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (180, 'Senior Sales Associate', 'Matern care for damag to fts from viral dis in mother, fts1');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (181, 'Environmental Specialist', 'Poisoning by antiallerg/antiemetic, assault, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (182, 'Financial Analyst', 'Complete traum amp of female extrn genital organs, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (183, 'Administrative Assistant IV', 'Segmental and somatic dysfunction of head region');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (184, 'Web Designer I', 'War op involving explosion of aerial bomb, civilian, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (185, 'Actuary', 'Burn unsp deg mult sites of unsp lower limb, ex ank/ft, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (186, 'Developer III', 'Displ suprcndl fx w intrcndl extn low end unsp femr, 7thB');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (187, 'Research Assistant IV', 'Actinomycotic encephalitis');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (188, 'Automation Specialist IV', 'West Nile virus infection, unspecified');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (189, 'Account Executive', 'Other marginal perforations of tympanic membrane, right ear');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (190, 'Information Systems Manager', 'Insect bite (nonvenomous), left hip');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (191, 'Registered Nurse', 'Neoplasm of uncertain behavior of brain, supratentorial');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (192, 'Assistant Professor', 'Partial traumatic amputation of left ear, sequela');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (193, 'Developer I', 'Disp fx of body of hamate bone, unsp wrs, 7thK');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (194, 'VP Quality Control', 'Contus/lac left cerebrum w LOC of unsp duration, init');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (195, 'Statistician IV', 'Unsp injury of unsp muscle and tendon at lower leg level');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (196, 'Compensation Analyst', 'Periprosth fx around internal prosth r ankle joint, subs');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (197, 'VP Product Management', 'Unspecified injury of blood vessel of right middle finger');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (198, 'Human Resources Assistant IV', 'Dermatopolymyositis, unspecified with myopathy');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (199, 'Marketing Assistant', 'Mast cell leukemia, in relapse');
insert into CARGOS (ID_CARGO, NOMBRE_CARGO, DES_CARGO) values (200, 'Biostatistician I', 'Oth cardiac comp of anesth during pregnancy, first trimester');
