create table CARGOS (
    ID_CARGO CHAR(50) not null,
    NOMBRE_CARGO CHAR(50) not null,
    DES_CARGO CHAR(50) not null,
    constraint PK_CARGOS primary key (ID_CARGO)
);

create table HISTORIA_CARGOS (
    HISTORIA_CARGO CHAR(50) not null,
    NOMBRE_HISTORIA_CARGO CHAR(50) not null,
    DESC_HISTORIA_CARGO CHAR(50) not null,
    ID_CARGO CHAR(50) not null,
    ID_EMPLEADO CHAR(50) not null,
    FECHA_INICIO_HISTORIA_CARGO DATE,
    FECHA_FIN_HISTORIA_CARGO DATE,
    constraint PK_HISTORIA_CARGO primary key (HISTORIA_CARGO)
);

create table DEPARTAMENTO (
    ID_DEPARTAMENTO CHAR(50) not null,
    NOMBRE_DEPARTAMENTO CHAR(50) not null,
    constraint PK_DEPARTAMENTO primary key (ID_DEPARTAMENTO)
);

create table HISTORIA_DEPARTAMENTOS (
    HISTORIA_DEPARTAMENTOS CHAR(50) not null,
    NOMBRE_HISTORIA_DEPARTAMENTOS CHAR(50) not null,
    DESC_HISTORIA_DEPARTAMENTOS CHAR(50) not null,
    ID_DEPARTAMENTO CHAR(50) not null,
    ID_EMPLEADO CHAR(50) not null,
    FECHA_INICIO_HISTORIA_DEPARTAMENTOS DATE,
    FECHA_FIN_HISTORIA_DEPARTAMENTOS DATE,
    constraint PK_HISTORIA_DEPARTAMENTOS primary key (HISTORIA_DEPARTAMENTOS)
);

create table HISTORIA_SALARIAL (
    HISTORIA_SALARIAL CHAR(50) not null,
    ID_EMPLEADO CHAR(50) not null,
    FECHA_INICIO_HISTORIA_SALARIAL DATE,
    FECHA_FIN_HISTORIA_SALARIAL DATE,
    MONTO_HISTORIA_SALARIAL MONEY,
    constraint PK_HISTORIA_SALARIAL primary key (HISTORIA_SALARIAL)
);

create table EMPLEADOS (
    EMPLEADOS_ID CHAR(50) not null,
    RUT CHAR(50) not null,
    CEDULA CHAR(50) not null,
    NOMBRE_EMPLEADO CHAR(50) not null,
    HOJA_DE_VIDA CHAR(50) not null,
    ID_ESTADO_EMPLEADO CHAR(50) not null,
    constraint PK_EMPLEADOS primary key (EMPLEADOS_ID)
);

create table NUMEROS_TELEFONO (
    NUMERO_TELEFONO_ID CHAR(50) not null,
    NUMERO_TELEFONO CHAR(50) not null,
    ID_EMPLEADO CHAR(50) not null,
    constraint PK_NUMERO_TELEFONO primary key (NUMERO_TELEFONO_ID)
);

create table ESTADOS_EMPLEADOS (
    ESTADO_ID CHAR(50) not null,
    NOMBRE_ESTADO CHAR(50) not null,
    VALOR_ESTADO integer,
    constraint PK_ESTADO_ID primary key (ESTADO_ID)
);

ALTER TABLE
    HISTORIA_CARGOS
ADD
    CONSTRAINT FK_ID_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGOS (ID_CARGO);

ALTER TABLE
    HISTORIA_CARGOS
ADD
    CONSTRAINT FK_ID_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (EMPLEADOS_ID);

ALTER TABLE
    HISTORIA_DEPARTAMENTOS
ADD
    CONSTRAINT FK_ID_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO);

ALTER TABLE
    HISTORIA_DEPARTAMENTOS
ADD
    CONSTRAINT FK_ID_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (ID_EMPLEADO);

ALTER TABLE
    HISTORIA_SALARIAL
ADD
    CONSTRAINT FK_ID_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (EMPLEADOS_ID);

ALTER TABLE
    EMPLEADOS
ADD
    CONSTRAINT FK_ESTADO_ID FOREIGN KEY (ID_ESTADO_EMPLEADO) REFERENCES ESTADOS_EMPLEADOS (ESTADO_ID);

ALTER TABLE
    NUMEROS_TELEFONO
ADD
    CONSTRAINT FK_ID_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (EMPLEADOS_ID);